--- #Tasks file for jenkins/tasks/main.yml
- name: Install Java OpenJDK
  yum: 
   name: 
    - java-1.8.0-openjdk

- name: Download Jenkins Repo
  get_url:
   url: http://pkg.jenkins-ci.org
   dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
   state: present
   key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum: 
   name: jenkins
   state: present

- name: Start & Enable Jenkins
  systemd:
   name: jenkins
   state: started
   enabled: true
