- name: Add GitLab repo to list of accessible repositories
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash warn=false

#- name: Set EXTERNAL_URL environment variable in .bashrc
#  lineinfile:
#    line: "export EXTERNAL_URL={{external_url}}"
#    path: /root/.bashrc
#    regexp: "export EXTERNAL_URL={{external_url}}"
#    state: present

#- name: Source the .basrc file
#  shell: source /root/.bashrc

- name: Install GitLab
  action: yum name="gitlab-ee" state=installed
  notify: Start GitLab Service
