- name: Install GraphicsMagick 
  yum: name=GraphicsMagick state=installed

- name: Install node version required by Rocket.Chat
  command: n 8.11.3

- name: Start and Enable MongoDB
  systemd: name=mongod state=started enabled=yes
  listen: start mongodb and rocket.chat
  
- name: Start and Enable Rocket.Chat
  systemd: name=rocketchat state=started enabled=yes daemon_reload=yes
  listen: start mongodb and rocket.chat
