---
- name: Configure GitLab Server
  hosts: gitlab
  gather_facts: no
  become: yes

  vars_prompt:
    - name: external_url
      prompt: "Enter an external URL:\n(The url you will use to access your GitLab installation)\n"
      default: "http://gitlab.emwg.com"
      private: no
  tasks:

  - name: Install tools for host management and troubleshooting 
    yum: name={{item}} state=installed
    with_items: [vim-enhanced,telnet,man-pages]

  - name: Add GitLab repo to list of accessible repositories
    shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash warn=false

  - name: Set EXTERNAL_URL environment variable
    shell: export EXTERNAL_URL={{external_url}}

  - name: Install GitLab
    action: yum name="gitlab-ee" state=installed
